### ISSUE TITLE
Sass throws error: EISDIR: File is a directory

### ISSUE THREAD

**Issue by pahund** [SUI-Components/sui-components#1189]
**Describe the bug**

To try out the SUI components, I've set up a little demo with create-react-app on Codesandbox.io:

https://codesandbox.io/s/adevinta-sui-0z6qj

So far, it is only supposed to show a couple of action buttons from the package _@s-ui/react-atom-action-button_.

I'm having trouble integrating the Sass theme in my main stylesheet. I did it [like this](https://codesandbox.io/s/adevinta-sui-0z6qj?file=/src/styles.scss):

_styles.scss_
```scss
@import '~@s-ui/theme/lib/index';
@import '~@s-ui/react-atom-action-button/lib/index';

.App {
  font-family: sans-serif;
  text-align: center;
}
```

When create-react-app tries to compile the stylesheet, it throws this error:

<img width="658" alt="image" src="https://user-images.githubusercontent.com/1639313/88295791-2d2e7400-ccfe-11ea-9e5b-c08af23d6dcb.png">

I've checked the code in _node_modules_, _lib/utils_ is indeed a directory.

**Steps to reproduce**

1. Go to https://codesandbox.io/s/adevinta-sui-0z6qj
2. See error on the “Problems” tab of the browser preview window

**Expected behaviour**

I expect the import of the Sass theme and the ActionButton atom to work properly, so that the browser preview window shows the buttons.

**Screenshots**

See above

**Environment / Context**
- Desktop
- Google Chrome 84

**Additional info**

Using latest version of node-sass, 4.14.1. My first guess was this may be a compatibility issue with Sass, but version 3 throws the same error.

**Comment by andresin87** [comment]
This is because the resolver of the sass modules does not have the 'scss' file extension `lib/utils.scss` and tries to import it as a directory `lib/utils`, which becomes `lib/utils/index.scss`

**Comment by pahund** [comment]
Thanks for your reply! My knowledge of Sass is rusty, can you give me a tip how to fix it? Do I have to eject the create-react-app?

**Comment by andresin87** [comment]
Of course not

Where can i find the project  you are working on ?

**Comment by pahund** [comment]
It's online: https://codesandbox.io/s/adevinta-sui-0z6qj

You can edit it right in your browser

**Comment by andresin87** [comment]
I think something like https://codesandbox.io/s/adevinta-sui-djzb3 should work. With react-app-rewired you can modify the webpack config of a cra without ejecting it. Codesandbox is using its own laucher, not the package.json given command. Try it on your local machine and let me know if it works.

**Comment by pahund** [comment]
Yup, thanks, that did the trick!
