### ISSUE TITLE
Api's Modal documentation not working

### ISSUE THREAD

**Issue by xaviermariaconejo** [SUI-Components/sui-components#1191]
**Describe the bug**
The api section of the documentation of the Modal components is not working

**Steps to reproduce**
1. Go to https://sui-components.now.sh/workbench/molecule/modal/documentation/api

**Expected behaviour**
See the full api documentation of that components

**Comment by turolopezsanabria** [comment]
Alright!  thanks, we are taking a look and fixing it.

**Comment by andresin87** [comment]
fixed in 
[https://github.com/SUI-Components/sui/pull/959](https://github.com/SUI-Components/sui/pull/959)
