### ISSUE TITLE
Can not apply ellipsis to button link

### ISSUE THREAD

**Issue by xaviermariaconejo** [SUI-Components/sui-components#1205]
**Is your iteration request related to a problem?**
I need to add ellipsis styles, the typical three dots, but the current component doesn't allows me to do that

**Describe the solution you'd like**
When it is a button with link design without href, it renders a button and inside a span, I can apply the correct styles to apply the ellipsis on the button, but the span breaks that styles. I would chose to remove that span, or add the style: display: inline-block, to fix it

**Comment by turolopezsanabria** [comment]
hm.. yup I see this :S 
we definitely have to find a solution (without a major release) for buttons rendered and styled as `a` links.

**Comment by xaviermariaconejo** [comment]
En la reunión de SUI-Components hemos comentado que este tipo de cambios, que son bastante particulares dentro del vertical, mejor que se queden dentro del vertical, con el approach que el propio vertical elija, desde componentes comunes dentro del vertical, clases de css, etc.

Y si hay una parte de estilos que se quieran aprovechar se pueden utilizar los estilos que te da SUI-Theme, desde clases hasta mixins.

Así que se cierra este ISSUE ✌️
