### ISSUE TITLE
Add loading state to Button

### ISSUE THREAD

**Issue by andresz1** [SUI-Components/sui-components#1209]
**Is your iteration request related to a problem?**

Buttons that trigger asynchronous actions might need a loading state and optionally a loading text.

**Describe the solution you'd like**

I think that would be nice to support this state through a `prop`. For example:

```jsx
<AtomButton isLoading />
// or
<AtomButton loadingText="Submitting" isLoading />
```

The loading state should:
- Display a spinner
- Optionally display a loading text
- Be disabled (setting `cursor` to `not-allowed` would be nice)

Proposed API:
|  Prop |   Type |  Description | Required  | 
|---|---|---|---|
|  isLoading |  boolean | If `true` should display loading state  | false  |
|  loadingText |  string | If `isLoading` is set to `true` and it's not empty should also display the text  |  false |

**Additional context**

The components shown above should look like:

<p align="center">
<img src="https://user-images.githubusercontent.com/6877967/91469605-e3ecb980-e893-11ea-8486-d28d7286dbde.png" />
</p>

Benchmark with other Design Systems Libraries:

- [base-ui](https://baseweb.design/components/button/#states)
- [braid](https://seek-oss.github.io/braid-design-system/components/Button)
- [chakra-ui](https://chakra-ui.com/button#button-loading-state)

**Comment by turolopezsanabria** [comment]
Very good idea, thanks for sharing.
Having a loading state for buttons has been in the conversation within UX for a while now.
Let's chat next week about this one.

**Comment by andresin87** [comment]
👍
