### ISSUE TITLE
button / basic displays icon in a new line with firefox

### ISSUE THREAD

**Issue by JoanClaret** [SUI-Components/sui-components#122]
Hi there, 
buttons are displayed incorrectly with firefox / mac:

![image](https://user-images.githubusercontent.com/886033/28704153-01318730-7369-11e7-84ba-c49452ddd2a8.png)

**Comment by midudev** [comment]
Which version of Firefox are you using? I can see them correctly. You might be using an old version of Firefox and it might be missing autoprefixes?

![image](https://user-images.githubusercontent.com/1561955/28705140-acf5c540-736e-11e7-9c52-785020fdd96a.png)

**Comment by JoanClaret** [comment]
@miduga  i'm using 45.0.1 . agree with you. looks like we are missing this version in autoprefixer

**Comment by JoanClaret** [comment]
outdated.
