### ISSUE TITLE
Checkbox Demo

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/sui-components#1241]
# Acceptance Criteria
The Checkbox demo viewed on sui-studio is not following the agreements.
It can be previewed on the following link:
[sui-studio checkbox DEMO](https://sui-components.now.sh/workbench/atom/checkbox/demo)

# Definition Of DONE
- [ ] Rename "Use Cases” to "States"
- [ ] Add description

><img src="https://avatars2.githubusercontent.com/u/13288987?s=200&v=4" alt="SUI Logo" width="150"/><img src="https://user-images.githubusercontent.com/1674036/95448749-18a86200-0964-11eb-82af-e36928e16936.jpg" alt="Adevinta Logo" width="150"/>

> SUIC-322

**Comment by andresin87** [comment]
Yes it is

**Comment by joneskj55** [comment]
Ok thanks, I'll submit a PR as soon as possible.

**Comment by joneskj55** [comment]
@andresin87 Just wanted to verify with you, should I be using `npm run co` to commit or am I ok to just commit with original git commands?

**Comment by andresin87** [comment]
Use npm run co plzz
The kind of mensage might be `doc`
