### ISSUE TITLE
RadioButton DEMO #SUIC-340

### ISSUE THREAD

**Issue by andresin87** [SUI-Components/sui-components#1244]
# Acceptance Criteria
The `RadioButton` demo viewed on sui-studio is not following the agreements.
It can be previewed on the following link:

# Definition Of DONE
- [ ] Rename "Use Cases” to "States"
- [ ] Add description

> ### Jira Task
> [SUIC-340](https://jira.scmspain.com/browse/SUIC-340)

**Comment by devppratik** [comment]
I am interested to work on this, can I be assigned on this

**Comment by devppratik** [comment]
> I am interested to work on this, can I be assigned on this

The second work that needs to be done is to add a description. Can you please tell me where to add the description - on the demo page or the readme page ?

**Comment by andresin87** [comment]
Description needs to be added only in the demo part.
