### ISSUE TITLE
Badge Counter: Add colour variation and add one more size

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1256]
**Is your iteration request related to a problem?**
Yes, we need to include badge counters in the Tabs, and for that we need an improved size and colour.

**Describe the solution you'd like**

* Add one more size: Large = size 24px default!, font-size Small
* Add a colour variation as new Prop: bg color Light: Default value Primary Light-3, text color: Primary 

**Additional context**

* These two changes are initially requested for Fotocasa Pro, but are valid for all themes as well
* This change is needed in order to include the badges in the Tabs

**Comment by nuria-isart** [comment]
This badge counters in Tabs have two states:
1. Highlighted or selected: we will use the Primary variation.
2. Rest or disabled: we will use this new variation:
-  Add a colour variation as new Prop: bg color Grey: Default value Grey Light-3 (#DCDCDC), text color: Grey

**Comment by AitorRodriguez990** [comment]
Hi there 👋 

@turolopezsanabria, this component has `Large` size yet, right? https://sui-components.now.sh/workbench/atom/badge/demo

**Comment by turolopezsanabria** [comment]
yes! 
the badge has Large size. The one that doesn't have Large is `Badge Counter`
https://sui-components.now.sh/workbench/molecule/badgeCounter/demo

> Hi there 👋
> 
> @turolopezsanabria, this component has `Large` size yet, right? https://sui-components.now.sh/workbench/atom/badge/demo

**Comment by AitorRodriguez990** [comment]
Oh! Then this iteration only applies to `MoleculeBadgeCounter` and not `AtomBadge`, right?

**Comment by turolopezsanabria** [comment]
Thanks @AitorRodriguez990
