### ISSUE TITLE
New component proposal - GRID

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1271]
**Is your component proposal related to a problem? Please describe.**
Hello, as discussed this is not URGENT, but it would be really handy to have a Grid as component.

**From the UX point of view, these are the requirements:**

* *The grid can't be styled:* For instance, it's shouldn't be possible to _paint_ the grid with a BG colour, or a Stroke.
* *Number of columns:* 12 (fixed, *NOT* customisable per Theme)
* *Responsive:* It must be possible to set a different number of columns per Breakpoint (12 columns for XS, 6 for M, 2 for L, etc)
* *Breakpoints:* To use the ones defined in SUI [Breakpoints|[https://github.com/SUI-Components/sui-theme/blob/master/src/layout/_breakpoints.scss]] (that are customisable per Theme)
* *Vertical alignment:* It should be possible to set the alignment to Top, Middle and Bottom
* *Gutters:* only 4 possible values
** none
** *S:* $w-base/2
** *M:* $w-base (to be added in [_spacing.scss|[https://github.com/SUI-Components/sui-theme/blob/master/src/settings/_spacing.scss]] with initial value 8px !default; )
** *L:* $w-base*2

*Not needed at least from UX side, but maybe worth to have for Development:*

* Column offset

In Jira: https://jira.scmspain.com/browse/SUIC-248

**Comment by klaufel** [comment]
Closed by #1295
