### ISSUE TITLE
Adjust the token "border-radius" everywhere

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1273]
**Is your iteration request related to a problem?**
The border-radius management across all components is a nightmare.
After a thorough analysis of the current status of Border-radius, we've decided to:

**Describe the solution you'd like**
1 - Set missing variables in SUI Theme ( $bdrs-s is missing for instance)

2 - Replace hardcoded values with the correct value defined in SUI Theme.
In every file where a border-radius has a hardcoded value.
- Initially, everything is listed in [this spreadsheet](https://docs.google.com/spreadsheets/d/15qDsbgGW6EDLhO5AaXnxQB_R3tGaoma_R7TcWzDQsa0/edit#gid=1195802274), but please double check if something is missing

3 - Replace $bdrs-base in the components with the correct value defined in SUI Theme.
Replace the border radius values set directly as $bdrs-base, by the correct value defined in the theme (probably $bdrs-m)

- in every file where a border-radius has $bdrs-base as value.
- Initially, everything is listed and coloured in light-blue in [this spreadsheet](https://docs.google.com/spreadsheets/d/15qDsbgGW6EDLhO5AaXnxQB_R3tGaoma_R7TcWzDQsa0/), but please double check if something is missing.

4 - Replace the settings-compat-v7 variables with the correct value defined in SUI Theme.
- https://github.com/SUI-Components/sui-theme/blob/master/src/settings-compat-v7/_box-style.scss
- https://github.com/SUI-Components/sui-theme/blob/master/src/settings-compat-v7/_components.scss
In every file where a v7 value is set
Initially, everything is listed and coloured in Yellow in [this spreadsheet](https://docs.google.com/spreadsheets/d/15qDsbgGW6EDLhO5AaXnxQB_R3tGaoma_R7TcWzDQsa0/), but please double check if something is missing.

5 - Refactor Border-radius component notification using the correct $bdrs values defined in SUI Theme.

In Jira: https://jira.scmspain.com/browse/SUIC-206

**Comment by xaviermariaconejo** [comment]
Borrar bdrd-none

**Comment by xaviermariaconejo** [comment]
I've done this for sui & real state, there are other verticals that are missing

**Comment by turolopezsanabria** [comment]
Duplicated
