### ISSUE TITLE
Component Badge - Iteration request: Add a new Prop "Design" 

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1298]
**Is your iteration request related to a problem?**
We need more flexibility for the component Badge. 
Specifically a design with solid "soft" is needed.

**Describe the solution you'd like**
Specific colour combination for the new Design "soft" will be provided below:

We suggest a new Prop "design", with a default value with what we currently have, and a new one: "Soft"

**Additional context**

- Component: https://sui-components.now.sh/workbench/atom/badge/demo
- Code of the component: https://github.com/SUI-Components/sui-components/tree/master/components/atom/badge

**Comment by nuria-isart** [comment]
**New Design "soft" combination in Fotocasa:**
The background of the badge should be in L4, this means:

- Accent L4: `#FCE8EE`
- Error L4: `#FCEBE8`
- Primary L4: `#EAEBF7`
- Success L4: `#E5F5EB`
- Warning L4: `#FEF4E6`

The letter colors in the badge should be in their solid version:

- Accent: `#E3165B`
- Error: `#E23515`
- Primary: `#303AB2`
- Success: `#00A544`
- Warning: `#F79500`
