### ISSUE TITLE
Component Documentation

### ISSUE THREAD

**Issue by xaviermariaconejo** [SUI-Components/sui-components#1311]
# Acceptance Criteria
The `Button` readme and api viewed on sui-studio is not correct. The prop "link" is not working, in the readme there is a example that is not correct. And in the API there is a definition and is not correct too. The correct way to use it is design="link", this way it works.

It can be previewed on the following link:
[sui-studio `Button`](https://sui-components.now.sh/workbench/atom/button/documentation/api)

# Definition Of DONE
 - [ ] Remove the "link" property in API
 - [ ] Fix the example of "link" in Readme

**Comment by turolopezsanabria** [comment]
Hola @xaviermariaconejo 
Can you confirm this issue has been resolved with the latest changes to the Button Component?

**This is the demo**

https://sui-components.vercel.app/workbench/atom/button/demo

**Comment by turolopezsanabria** [comment]
Already fixed
