### ISSUE TITLE
Iterate Avatar to support a new size: 40px

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1329]
**Is your iteration request related to a problem?**
We need a size that is not currently available

**Describe the solution you'd like**
The missing one is 40px

I suggest:
XS: 24px --- NEW!
S: 32px
M: 40px --- NEW!
L: 48px
XL: 64px
XXL: 80px

**Additional context**
You can see the need in action in this prototype:
https://playground.turo.vercel.app/navBar

**Comment by xaviermariaconejo** [comment]
Done in the mentioned PR
