### ISSUE TITLE
Demo not working as expected: Grid

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1354]
**Describe the bug**

Grid demo not working as expected

**Steps to reproduce**

1. https://sui-components.now.sh/workbench/layout/grid/demo

**Expected behaviour**

The columns should have the correct width

**Screenshots**

![Screenshot 2020-12-16 at 11 47 04](https://user-images.githubusercontent.com/23620759/102338649-6d83dc80-3f94-11eb-9b3b-b18472a2d146.png)

**Additional info**

![Screenshot 2020-12-16 at 11 47 26](https://user-images.githubusercontent.com/23620759/102338699-7bd1f880-3f94-11eb-9031-5ce5473e5207.png)

**Comment by klaufel** [comment]
Fixed in the previously deployment!
