### ISSUE TITLE
Demo toggles don't work

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1432]
**Describe the bug**
The toggle buttons don't do anything (check video attached)

**Steps to reproduce**
1. Go to 'https://sui-components.now.sh/workbench/atom/button/demo'
2. Scroll down to the bottom of the page
3. Interact with the toggle buttons

**Expected behaviour**
Toggle buttons should update the demo

**Screenshots / Video**
https://user-images.githubusercontent.com/23620759/112325341-e3929080-8cb3-11eb-8925-ea000c2c98ce.mov

**Comment by andresin87** [comment]
Solved with
https://github.com/SUI-Components/docs-components/commit/2cb4588c57f375b1c1cbb782a440f30e4407c0bc#diff-7b12be43febc6e18259dd77c004315b4143d570234e0f15acf5f9d7b79c371b5
and also
https://github.com/SUI-Components/sui-components/commit/33399d8a2549ff20883935749d41b770c41ca9a7

**Comment by turolopezsanabria** [comment]
👏🏼  thanks!
