### ISSUE TITLE
Subtle defect - Remove underline decoration in actionable Tags

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1461]
**Describe the bug**
The actionable tags have a underline text decoration, and that's not correct 

**Steps to reproduce**
1. Go to https://sui-components.vercel.app/workbench/atom/tag/demo
2. Scroll down to the demos for "Actionable"

**Expected behaviour**
Actionable tags should never have underline decoration

**Screenshots**
![Screenshot 2021-04-13 at 13 05 00](https://user-images.githubusercontent.com/23620759/114542965-dc2e2980-9c58-11eb-9a73-d2e9780fd273.png)

**Comment by jordevo** [comment]
Closing the issue because the fix has been merged and released.
