### ISSUE TITLE
Demo is not working: PhotoUploader

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1613]
**Describe the bug**

The demo for the component PhotoUploader is blank

**Steps to reproduce**

1. Go to https://sui-components.vercel.app/workbench/molecule/photoUploader/demo
2. See error

**Expected behaviour**

The demo should work and follow the demo guidelines

**Screenshots**

![demo photo Uploader not working](https://user-images.githubusercontent.com/23620759/125937671-598eb2a0-2c20-4136-9dcc-848069ddc11e.png)

**More info**

**Comment by andresin87** [comment]
solved
