### ISSUE TITLE
Tag close icon

### ISSUE THREAD

**Issue by beatrizip** [SUI-Components/sui-components#1622]
**Describe the bug**
The tag close icon has a wrong color

**Steps to reproduce**
1. Go to closeable tags
2. See the close icon

**Expected behaviour**
When not in hover status the icon color is dark

**Screenshots**
<img width="147" alt="Captura de pantalla 2021-07-22 a las 9 28 45" src="https://user-images.githubusercontent.com/16401219/126603900-a16195d7-7ebe-4744-9ac4-f3f3e29ae4d9.png">

**Comment by turolopezsanabria** [comment]
closed here!
https://github.com/SUI-Components/sui-components/pull/1634
