### ISSUE TITLE
Table DEMO - Needs a refactor

### ISSUE THREAD

**Issue by turolopezsanabria** [SUI-Components/sui-components#1760]
The component [Table](https://sui-components.vercel.app/workbench/atom/table/demo) needs a complete refactor.

- [ ] It should use the Docs Library
- [ ] Every item from the API tab should have an example
- [ ] When using components inside the demo (such as a button), they have to be SUI Components

**Comment by andresin87** [comment]
Reopened. It still needs the refactor
