### ISSUE TITLE
Sui-Title dinamic classNames

### ISSUE THREAD

**Issue by davecarter** [SUI-Components/sui-components#345]
The Sui-Title component has a [fixed class declaration](https://github.com/SUI-Components/sui-components/blob/master/components/title/basic/src/index.js#L16) and IMHO it should be composed via its `className` props value. Like:
```javascript
<h1 className={`${className}-title`}>{title}</h1>
```
If we do so we'll be able to re-use the same component multiple times in the same page without affecting one each other.

**Comment by JoanClaret** [comment]
Be careful, if you remove this class you'll loose this declarations:

https://github.com/SUI-Components/sui-components/blob/master/components/title/basic/src/index.scss#L6

i guess we should find another way to re-use it!

**Comment by JoanClaret** [comment]
wrong button, sorry for closing it 
: )

**Comment by davecarter** [comment]
No its ok! We should close this issue.
As you mentioned, we should avoid the use of classNames. Instead we need to have a detailed definition of all possible headings styles (h1, h2, h3.. ) and all its possible variations: primary, secondary, tertiary...

We should create a new `SUI-atom-title` component instead.
:)
