### ISSUE TITLE
FormTextInput component needs KeyBoard events

### ISSUE THREAD

**Issue by elhoucine** [SUI-Components/sui-components#359]
Hi guys, terrific job 👍 

I think It would be awesome if `FormTextInput` provides some keyBoard Events like `onKeyPress`. The only event provided so far is `onChange`.

Or maybe a way to support all possible events supported by the native input.

**Comment by davidbarna** [comment]
Hi @elhoucine,
When you build a component, you develop only "the features you need at the moment". Afterwards if someone wanna use this component but needs something more, he's in charge of adding this feature to use it.
Same system for new components. We only develop what's mentioned in spec (the paper). This way we ensure we don't spend time developing stuff that may never be used.
Let me know if you need further info.

**Comment by elhoucine** [comment]
Hi @davidbarna, 

So in my case, I am playing with the sui-components in a side project, should I go ahead and submit a PR for adding that specific event?

In my opinion, this is more a limitation added by the component wrapper rather than a "feature you need at the moment", I am talking from an open source point of view.

**Comment by davidbarna** [comment]
Yes ! Go ahead  and thanks in advance for your contribution  !
