### ISSUE TITLE
atom/button Error fullWidth on using atom buttons with fullWidth

### ISSUE THREAD

**Issue by carlesnunez** [SUI-Components/sui-components#511]
We have seen an error on using sui-atom-button in link mode with fullWidth enabled. The error is only show on build version (not linking) and once we use prop link and fullWidth together.

The error is that react says that we are passing a fullWidth property to a DOM element <a>. In fact, we are passing it as we have a default linkFactory <a> on our Button.js file that does a {...rest} passing the whole props to the <a> tag.

https://github.com/SUI-Components/sui-components/blob/4f18f58fd2fbddcf9d3bc7cf73d6f668b4cda5d6/components/atom/button/src/Button.js#L56

**Comment by carlesnunez** [comment]
I'll try to made a fix later

**Comment by carlesnunez** [comment]
@juanmaguitar I have not time to do that so if you could fix the bug it will be so helpful to me. Is strange that the error only is showed on bundled versions non the dev ones.

If you need any help, please ask me :)

**Comment by juanmaguitar** [comment]
Issue fixed on commit [b5eff60e52f4457a5417f186ce90a28a64d890f5](https://github.com/SUI-Components/sui-components/pull/510/commits/b5eff60e52f4457a5417f186ce90a28a64d890f5) that is part of the PR #510
