### ISSUE TITLE
Can't specify rel tag to Button of type link

### ISSUE THREAD

**Issue by juanmendez90** [SUI-Components/sui-components#657]
I need to specify a rel different to `noopener` for a link with a `href=mailto` , this is because `target=_blank` in combination with `rel=noopener` and `href=mailto` doesn't work on Android browsers, it opens an empty tab instead of the email app
I found that the rel is hardcoded here https://github.com/SUI-Components/sui-components/blob/d57c714a55ff906135bfd17545cda5d969a5f909/components/atom/button/src/Button.js#L22

Is it possible to update the button to set a custom rel?

**Comment by jcger** [comment]
yes, ofc. Just try to maintain backwards compatibility please
