### ISSUE TITLE
atom/card Add responsive functionality

### ISSUE THREAD

**Issue by rmoralp** [SUI-Components/sui-components#664]
**AtomCard** could be horizontal or vertical but it can't be responsive (vertical in mobile and horizontal in desktop).

In coches.net we need this functionality to create or vehicle component in order to decouple our core page "ads list"

It could be a "responsive" prop that adds a modifier class with a media query. Not compatible with "vertical" prop.

Is it possible to iterate **AtomCard** to add this functionality?

**Comment by JoanClaret** [comment]
+1 to add a `responsive` prop
