### ISSUE TITLE
atom/tag class naming convention issue

### ISSUE THREAD

**Issue by rmoralp** [SUI-Components/sui-components#674]
AtomTag could has two icons:

![image](https://user-images.githubusercontent.com/5390428/56356434-2e0e5700-61d9-11e9-95b6-f12cdbad0c68.png)

The icon on the left has "sui-AtomTag-icon" class
The icon on the right has "sui-AtomTag-secondary-icon" class

This class names are wrong. It should be something similar to "sui-AtomTag-iconLeft" and "sui-AtomTag-iconRight"

**Comment by nucliweb** [comment]
@rmoralp we can close this issue, right?
