### ISSUE TITLE
molecule/collapsible: Custom background color

### ISSUE THREAD

**Issue by nucliweb** [SUI-Components/sui-components#680]
We need a property to define a custom background color.

![collapsible](https://user-images.githubusercontent.com/1307927/56641418-a2337980-6675-11e9-8481-3b0fd499c512.jpg)

**Comment by adriadoz** [comment]
La variable del background está en el componente como default, estaría bien añadir las variables de componente en el README para darles visibilidad.

**Comment by nucliweb** [comment]
I will add this option to the documentation.

```
// Custom background-color
$bgc-collapsible-container: #f5f0ec;
```
