### ISSUE TITLE
atom/input: Non focusable elements

### ISSUE THREAD

**Issue by davecarter** [SUI-Components/sui-components#715]
## Issue summary
As stated in [Accesibility and inclusion guidelines](https://confluence.schibsted.io/pages/viewpage.action?pageId=51259903), in its first rule: *Every interactive element should be focusable*.

#### The Problem:
- Currenty `sui-atom-input` component has the pseudoClass `:focus` with all visuals disabled:

```
.sui-AtomInput-input[type='radio']:focus,
.sui-AtomInput-input[type='checkbox']:focus {
    border: 0;
    box-shadow: none;
    outline: 0 none;
}
```
Users are unable no navigate through form elements using `tabIndex` due to this lack of visual feedback (functionality is not affected)

- Example of **selected** checkbox:
<img width="173" alt="Screenshot 2019-06-19 at 16 20 43" src="https://user-images.githubusercontent.com/10925540/59774430-baa7c500-92af-11e9-807f-3b176ec4ac48.png">

#### The solution:
- Define a similar styling as it already has its `type=text` form:
<img width="338" alt="Screenshot 2019-06-19 at 16 32 53" src="https://user-images.githubusercontent.com/10925540/59774624-0eb2a980-92b0-11e9-8593-8bb6ff39365d.png">

```
.sui-AtomInput-input:focus {
    border: 1px solid #30832f;
    box-shadow: 0 0 3px 0 #2b91c1;
    outline: 0 none;
}
```

Thanks

**Comment by juanmaguitar** [comment]
_To be taken into account_

The styles of the focus input and all input related components which includes:

- `AtomInput`
- `MoleculeInputField`
- `MoleculeSelect`
- `MoleculeAutosuggest`

are centralized in https://github.com/SUI-Components/sui-theme/blob/master/src/components/atom/input/ as a placeholder `sui-atom-input-input-focus`

```
%sui-atom-input-input-focus {
  border: $bd-atom-input;
  box-shadow: $bxsh-atom-input;
  outline: 0 none;
}
```

which is applied in each input-like component.

This (and also **the disabling of the style of the native focus**) was done to assure:
- the focus styles are aligned w/ the ones represented in the paper and using variables in the sui-theme
- the focus styles are the same always no matter the browser
- we can share the focus styles across all input-like components
