### ISSUE TITLE
Molecule/Select doesn't open the dropdown when clicking in the box in Firefox

### ISSUE THREAD

**Issue by devictoribero** [SUI-Components/sui-components#863]
**Describe the bug**
The expected behavior of the `Molecule/Select` component is to open the options when clicking the box. It doesn't happen in Firefox, it only opens the options when clicking the down arrow ⬇️ .

**Steps to reproduce**
1. Using Firefox go to https://sui-components.now.sh/workbench/molecule/select/demo
2. Click on any box
3. See the bug

**Expected behaviour**
When clicking the box, the dropdown should be opened as it happens in `Chrome`

**Environment / Context**
- Desktop or Mobile? Both
- Browser and version Firefox

**Comment by JoanClaret** [comment]
Tested in Firefox 69.0 (64-bit) with mac and it's also failing

**Comment by devictoribero** [comment]
Already solved
