### ISSUE TITLE
The href prop of Link component should not receive a boolean value.

### ISSUE THREAD

**Issue by giodelabarrera** [SUI-Components/sui-components#874]
**Describe the bug**
`href` prop of `<Link>` should not receive a boolean value.

**Steps to reproduce**
Use a `<Button >` with next props:
```jsx
<Button link href="" disabled>Hello</Button>
```
View the console in the demo: https://codesandbox.io/s/exciting-leavitt-ww5oo

**Expected behaviour**
Shouldn't show warnings by console

**Screenshots**
![Captura de pantalla 2019-11-19 a las 14 09 09](https://user-images.githubusercontent.com/1263588/69149165-31065880-0ad6-11ea-8bd0-fbdab8f87bbb.png)

**Bug found
https://github.com/SUI-Components/sui-components/blob/master/components/atom/button/src/Button.js#L20

**Comment by nucliweb** [comment]
I understand the problem but, what is the use case to use a button as a link without `href`?

We can change this
```
href={!disabled && href}
```

to this
```
href={!disabled && href ? href : ''}
```

**Comment by giodelabarrera** [comment]
Hi @nucliweb, totally true with this `I understand the problem but, what is the use case to use a button as a link without href?`. In fact I think that the determining factor for a button to be built as an anchor is simply if it receives the `href` prop.  But currently if I only had `link` and` disabled` an error was already happening because I was prepared so that it could work with only these two `props` but it gave a console error.

**Comment by giodelabarrera** [comment]
Resolved in https://github.com/SUI-Components/sui-components/pull/893
