### ISSUE TITLE
molecule/modal - back button does not close modal

### ISSUE THREAD

**Issue by rmoralp** [SUI-Components/sui-components#912]
**Describe the bug**
Tapping the system back button or clicking back button in desktop browsers and safari mobile are not closing opened modal. It just navigate back to previous url.

**Expected behaviour**
As a standard, it back button should close modal if it is open, if not navigate to previous history url.
See Material Design dialog behaviour specs: https://material.io/components/dialogs/#behavior

**Environment / Context**
- Desktop and Mobile

**Comment by turolopezsanabria** [comment]
boom, nice discovery, it was not under my radar.
Yes, I think too it should / could be controlled from SUI Component itself
