### ISSUE TITLE
MoleculeSelect arrow key navigation bug

### ISSUE THREAD

**Issue by AgonisticKatai** [SUI-Components/sui-components#940]
**Describe the bug**
Navigating with the arrow keys through the items of a select, when we reach the second item, the select closes unexpectedly

**Steps to reproduce**
1. Go to https://sui-components.now.sh/workbench/molecule/selectField/demo
2. Click on a SelectField
3. Scroll down with arrow keys

**Expected behaviour**
We need to be able to navigate through the select items using the arrow keys on the keyboard

**Screenshots**
![Kapture 2020-01-23 at 9 43 25](https://user-images.githubusercontent.com/31726966/72968958-df739600-3dc4-11ea-98d9-617918eda1ba.gif)

**Environment / Context**
- Desktop

**Additional info**
The error can be identified in the next line of code, by seeing how from the second time we click on the down arrow key, the reference `refsMoleculeSelectOptions.current` includes the items correctly, but when mapped, it returns a `null` for each item
https://github.com/SUI-Components/sui-components/blob/4a700850af1101247006e0cedc6a01ffb54761d2/components/molecule/select/src/index.js#L117

**Comment by turolopezsanabria** [comment]
hey! 
This has been already fixed here: https://github.com/SUI-Components/sui-components/pull/1079
Thnx for reporting @AgonisticKatai
