### ISSUE TITLE
Deprecate SUI Ad L or just develop it?

### ISSUE THREAD

**Issue by kikoruiz** [SUI-Components/sui-components#96]
Hi mates, since here in Schisbsted Spain we are migrating to a new advertising platform (AppNexus) it's clear that this component https://github.com/SUI-Components/sui-components/tree/master/components/ad/l makes no sense. Should we deprecate it or even develop it in order to make it "AppNexus compliant"?

**Comment by carlosvillu** [comment]
I think it could migrated to AppNexus.

I maybe this component could do the job https://github.schibsted.io/spt-advertising/ads-js-sdk/blob/master/packages/react-ad-tags/README.md

**Comment by turolopezsanabria** [comment]
Hello. Is this issue current?
If not, could we close it?

**Comment by nucliweb** [comment]
I thinks that we can close it, and reopen if is necessary 😊
